language: node_js

node_js:
- 8

before_install:
- sudo add-apt-repository ppa:jonathonf/python-3.6 -y
- sudo apt-get update
- sudo apt-get install python3.6 python3.6-dev -y
- curl -s https://bootstrap.pypa.io/get-pip.py | sudo python3.6

cache:
  yarn: true
  directories:
  - node_modules
  pip: true

install:
- sudo python3.6 -m pip install -r requirements.txt
- yarn

script:
- grablib
- yarn lint
- yarn test -- --coverage
- yarn build

after_success:
- ls -lha
- bash <(curl -s https://codecov.io/bash)
