language: node_js

node_js:
- 8

before_install:
- sudo add-apt-repository ppa:jonathonf/python-3.6 -y
- sudo apt-get update
- sudo apt-get install python3.6 python3.6-dev -y
- curl -O https://bootstrap.pypa.io/get-pip.py
- sudo python3.6 get-pip.py

cache:
  yarn: true
  directories:
  - node_modules

install:
- yarn
- sudo python3.6 -m pip install -r requirements.txt
- grablib

script:
- yarn lint
- yarn test
- yarn build

after_success:
- ls -lha
#- bash <(curl -s https://codecov.io/bash)
